### ISSUE TITLE
Port25 PowerMTA MailWizz bounce handler  

### ISSUE THREAD

**Issue by masharif46** [magicdude4eva/port25-bouncehandler#12]
i am install and test PowerMTA with bounce handler it's successfully communicate.  I am send Campaign with Invalid Email & invalid Email Automatically Unsubscribed from MailWizz subscriber List . My Problem Bounce not showing in MailWizz DASHBORAD``Check both Screenshot 
![bounce and fbl](https://user-images.githubusercontent.com/13065284/29572209-6bf39d6a-877d-11e7-96c8-95511206edb2.png)
![unsubscribed](https://user-images.githubusercontent.com/13065284/29572210-6bff69ec-877d-11e7-96a2-44a92ff52f3a.png)

**Comment by magicdude4eva** [comment]
The Port25 bouncehandler does an unsubscribe of the email from all lists and the MailWizz API does unfortunately not provide as bounce code or mark an unsubscribe as bounced. This will unfortunately only be reflected in the Unsubscribe rate.

I will reach out to Twisted again and see if there is a way to mark an unsubscribe as "bounced".

**Comment by masharif46** [comment]
Bro, Thanks for Reply .

**Comment by magicdude4eva** [comment]
@masharif46: A pre-release is available here. Please read notes carefully and ensure that you make the correct changes - https://github.com/magicdude4eva/port25-bouncehandler/releases/tag/1.2

**Comment by masharif46** [comment]
Thanks  ! I will Try. @magicdude4eva

**Comment by masharif46** [comment]
Hello @magicdude4eva    i am complete all Process But Nothing Changed .  Bounce not showing in MailWizz DASHBORAD

![bounce and fbl](https://user-images.githubusercontent.com/13065284/29627664-a4025390-8854-11e7-8945-40fa784f34a4.png)

**Comment by magicdude4eva** [comment]
Check your log files. It is working if you followed instructions. I have it running like this for the last 10 hours without a problem.

**Comment by masharif46** [comment]
OK , Thanks @magicdude4eva   , Can you give me ur skype ID ?

**Comment by masharif46** [comment]
Hello bro ,Can you give me ur skype ID ?  my Skype : masharif46,  @magicdude4eva 
There is no error . 
unsubhandler.log
pmta-bounce-handler.log
fbl-processor.log

**Comment by magicdude4eva** [comment]
@masharif46: I don't do Skype support. I also don't believe that there is no error unless the setup was not done properly (i.e. Port25 config for acct-file / feedback-loop-processor. 

I suggest that you attach all log-files to this issue (just redact any private/sensitive info) and then I can have a look at. AFAIK there are now 3 installations (excluding mine) using this release without issue.

**Comment by masharif46** [comment]
Thanks bro , @magicdude4eva 
Please check config 👍 
[config.txt](https://github.com/magicdude4eva/port25-bouncehandler/files/1247838/config.txt)

**Comment by magicdude4eva** [comment]
This looks fine. Check /var/log/pmta/pmta.log for errors. Provide me with a private Gist of your log files: 
```
/var/log/pmta/pmta-bounce-handler.log
/var/log/pmta/fbl-processor.log
/var/log/pmta/unsubhandler.log
```

Also do a `tail -f /var/log/pmta/pmta.log` and then a `pmta reload` and private Gist the output of the tail.

**Comment by masharif46** [comment]
Hello Bro, @magicdude4eva 

This log file

[fbl-processor.txt](https://github.com/magicdude4eva/port25-bouncehandler/files/1247910/fbl-processor.txt)
[log.txt](https://github.com/magicdude4eva/port25-bouncehandler/files/1247911/log.txt)
[pmta-bounce-handler.txt](https://github.com/magicdude4eva/port25-bouncehandler/files/1247908/pmta-bounce-handler.txt)
[unsubhandler.txt](https://github.com/magicdude4eva/port25-bouncehandler/files/1247909/unsubhandler.txt)

**Comment by magicdude4eva** [comment]
There are errors - in pmta.log:
```
2017-08-24 12:09:20 Error waiting for "/usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php --logfile=/var/log/pmta/fbl-processor.log": to exit: Timed out
```

Run this and post output `echo "test@test.com" | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php --debug`

**Comment by masharif46** [comment]
[root@server ~]# echo "test@test.com" | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php --debug
PHP Notice:  Constant MAILWIZZ_API_PUBLIC_KEY already defined in /opt/pmta/bouncehandler/setup.php on line 61
PHP Notice:  Constant MAILWIZZ_API_PRIVATE_KEY already defined in /opt/pmta/bouncehandler/setup.php on line 62
PHP Notice:  Constant MAILWIZZ_ENDPOINT_URL already defined in /opt/pmta/bouncehandler/setup.php on line 63
[24/Aug/2017 06:51:23] ------------------------------------------------------------------
[24/Aug/2017 06:51:23] Port25 PowerMTA bounce-handler
[24/Aug/2017 06:51:23] (C) 2016 Gerd Naschenweng  http://github.com/magicdude4eva
[24/Aug/2017 06:51:23] ------------------------------------------------------------------
[24/Aug/2017 06:51:23] Handling bounce categories=bad-mailbox,bad-domain,routing-errors,inactive-mailbox,spam-related
[24/Aug/2017 06:51:23] Bounce-provider: Interspire, initialising
[24/Aug/2017 06:51:23]    Skipped - not configured!
[24/Aug/2017 06:51:23] Bounce-provider: MailWizz, initialising
[24/Aug/2017 06:51:23]    Endpoint-URL=https://xxxxxxxxxxx/api/index.php
[24/Aug/2017 06:51:23]    MailWizz enabled!
[24/Aug/2017 06:51:23] Bounce-provider: MailWizz, complete
[24/Aug/2017 06:51:23] Feedback-provider: initialising
[24/Aug/2017 06:51:23] Feedback-provider: complete
[24/Aug/2017 06:51:23] Initialising RRD reporting via /var/log/pmta/pmta.rrd
[24/Aug/2017 06:51:23] Starting bounce processing
[24/Aug/2017 06:51:23]    MailWizz: Skipping test@test.com, already unsubscribed!
[24/Aug/2017 06:51:23] Completed bounce processing! Total records=1, processed=1, skipped=0

**Comment by magicdude4eva** [comment]
Two things:
1) From the output it does not look like you have the 1.2 code - the banner should say `(C) 2016-2017....` - please have a look at the ZIP file and verify that code is from August 2017:
![image](https://user-images.githubusercontent.com/1632781/29654474-a78b5c06-88ad-11e7-965f-ce18a282199b.png)

2) There seems to be duplicate constant definitions in your `/opt/pmta/bouncehandler/setup.php` - clean it up.

**Comment by masharif46** [comment]
Hey bro , @magicdude4eva  

for Testing I am Delete all log file from  /var/log/pmta/
Then run --
service pmta stop  
pmtad --debug
service pmta start 
auto generate only this log file .

/var/log/pmta/fbl-processor.log
/var/log/pmta/log
/var/log/pmta/pmta-bounce-handler.log
/var/log/pmta/pmta-startuperr.log
/var/log/pmta/pmta.rrd
/var/log/pmta/pmtahttp.log

This file not create & previous this file create manually  /var/log/pmta/unsubhandler.log

then run this file.

[root@server ~]# echo "test@test.com" | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php --debug
[24/Aug/2017 08:07:51] ------------------------------------------------------------------
[24/Aug/2017 08:07:51] Port25 PowerMTA bounce-handler
[24/Aug/2017 08:07:51] (C) 2016-2017 Gerd Naschenweng  https://github.com/magicdude4eva
[24/Aug/2017 08:07:51] ------------------------------------------------------------------
[24/Aug/2017 08:07:51] Handling bounce categories=bad-mailbox,bad-domain,routing-errors,inactive-mailbox,spam-related,policy-related
[24/Aug/2017 08:07:51] Soft-bounce categories=bad-configuration,bad-connection,content-related,invalid-sender,other,policy-related,quota-issues,spam-related,virus-related
[24/Aug/2017 08:07:51] Bounce-provider: Interspire, initialising
[24/Aug/2017 08:07:51]    Skipped - not configured!
[24/Aug/2017 08:07:51] Bounce-provider: MailWizz, initialising
[24/Aug/2017 08:07:51]    Endpoint-URL=https://xxxxxxxxxxxxx/api/index.php
[24/Aug/2017 08:07:51]    MailWizz enabled!
[24/Aug/2017 08:07:51] Bounce-provider: MailWizz, complete
[24/Aug/2017 08:07:51] Feedback-provider: initialising
[24/Aug/2017 08:07:51] Feedback-provider: complete
[24/Aug/2017 08:07:51] Initialising RRD reporting via /var/log/pmta/pmta.rrd
[24/Aug/2017 08:07:51] Starting bounce processing
[24/Aug/2017 08:07:51]    MailWizz: Skipping test@test.com, already unsubscribed!
[24/Aug/2017 08:07:51] Completed bounce processing! Total records=1, processed=1, skipped=0

also getting sam e error in  /var/log/pmta/log

2017-08-24 14:02:38 SMTP Listener at 0.0.0.0:587 starting
2017-08-24 14:02:38 Error waiting for "/usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php": to exit: Timed out
2017-08-24 14:02:38 Error waiting for "/usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php --logfile=/var/log/pmta/fbl-processor.log": to exit: Timed out

**Comment by magicdude4eva** [comment]
It could be a Port25 version issue (I know that it works on `PowerMTA v4.5rXX`. PHP should be on 5.6.x.

The "Timed out" hints that the PHP script does not complete. I have unfortunately not seen this before and suggest to review your PMTA configs, versions and PHP installation. 

To rule out that the time out is related to the bounce-scripts, just create a dummy "test.php" which outputs something to systemout and then change your Port25 config to see if this also fails (then you know it is a setup issue elsewhere).

**Comment by masharif46** [comment]
hi bro, @magicdude4eva 

[root@server ~]# php -v
PHP 5.6.31 (cli) (built: Jul  6 2017 08:16:47)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

can you tell me about php configuration ?

pmta 4.0

**Comment by magicdude4eva** [comment]
I think you need to upgrade to PMTA 4.5rXX. I will not be able to support 4.0.

**Comment by masharif46** [comment]
OK Bro , I will upgrade @magicdude4eva

**Comment by magicdude4eva** [comment]
I am closing this, as the bounce-processing feature has been added and verified working by 3 different MailWizz/Port25 users (all on latest version of MailWizz and Port25 R4.5r8-10).

I am unfortunately not able to help with Port25 configurations / upgrades etc as those are typically very specific. I urge to read through the documentation as well as the setup.php comments.

Mail is difficult and these scripts do require some basic technical skill / Linux knowledge.

**Comment by masharif46** [comment]
Hello Bro ! @magicdude4eva  Port25 PowerMTA MailWizz bounce handler working on  PowerMTA 4.5r8 ? or work only PowerMTA 4.5r10 > Please let me know. Thank You !

**Comment by masharif46** [comment]
Wow ! I am so happy now . I am Upgraded PowerMTA 4.5r10  And Now Working  Port25 PowerMTA MailWizz bounce handler, Many Many Thanks Both big bro @magicdude4eva  @twisted1919  , Now Testing Abuse complaints , How to Test Abuse complaints ?

![pmta](https://user-images.githubusercontent.com/13065284/29994763-f62e733c-8ff8-11e7-859b-d3cb0510facf.jpg)

**Comment by twisted1919** [comment]
@jjoao07 - i can answer for this, it will process the bounces after the campaign has been sent. What you are after is a list cleaning service, to clean your email list before sending it to amazon.

**Comment by jjoao07** [comment]
Hi bro @twisted1919 ,
thanks for clarifying, I was checking on backend => store, and i find out that,
there some extensions, which looks like does the job.
this one
MailWizz EMA integration with TheChecker.co
and MailWizz EMA integration with EmailListVerify.com

So my worries about those extensions, for now, is not knowing if it is possible to integrate the extension, to check any list from default while uploading, and to be available for all customers, without them having to signup account with the third party.

I just wanted something straightforward,

So not sure if is it possible or not!

**Comment by shabsshab** [comment]
Iam unable to get  bounce in mailwizz when I send email to ss1232d@gmail.com which does not exist
Find the server details in below and please help

[root@server bouncehandler]# php -v
PHP 5.6.38 (cli) (built: Sep 12 2018 09:02:11)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

[root@server bouncehandler]# echo "ss1232d@gmail.com" | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php --debug
[20/Oct/2018 13:46:09] ------------------------------------------------------------------
[20/Oct/2018 13:46:09] Port25 PowerMTA bounce-handler
[20/Oct/2018 13:46:09] (C) 2016-2017 Gerd Naschenweng  https://github.com/magicdude4eva
[20/Oct/2018 13:46:09] ------------------------------------------------------------------
[20/Oct/2018 13:46:09] Handling bounce categories=bad-mailbox,bad-domain,routing-errors,inactive-mailbox,spam-related,policy-related
[20/Oct/2018 13:46:09] Soft-bounce categories=bad-configuration,bad-connection,content-related,invalid-sender,other,policy-related,quota-issues,spam-related,virus-related
[20/Oct/2018 13:46:09] Bounce-provider: MailWizz, initialising
[20/Oct/2018 13:46:09]    Endpoint-URL=http://sendboxpro.win/mw/api/
[20/Oct/2018 13:46:09]    MailWizz enabled!
[20/Oct/2018 13:46:09] Bounce-provider: MailWizz, complete
[20/Oct/2018 13:46:09] Starting bounce processing
[20/Oct/2018 13:46:09]    MailWizz: Failed looking up record ss1232d@gmail.com with status=error
[20/Oct/2018 13:46:09] Completed bounce processing! Total records=1, processed=1, skipped=0
[root@server bouncehandler]#

[root@server bouncehandler]# cat /var/log/pmta/acct-2018-10-20-0000.csv
type,timeLogged,timeQueued,orig,rcpt,orcpt,dsnAction,dsnStatus,dsnDiag,dsnMta,bounceCat,srcType,srcMta,dlvType,dlvSourceIp,dlvDestinationIp,dlvEsmtpAvailable,dlvSize,vmta,jobId,envId,queue,vmtaPool
b,2018-10-20 04:14:05-0500,2018-10-20 04:14:05-0500,return@server.box01.pw,ss1232d@gmail.com,,failed,5.1.1 (bad destination mailbox address),smtp;550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser p79-v6si26073660pfj.244 - gsmtp,gmail-smtp-in.l.google.com (74.125.142.27),bad-mailbox,smtp,sendboxpro.win (107.175.127.143),smtp,198.46.144.28,74.125.142.27,"ENHANCEDSTATUSCODES,PIPELINING,CHUNKING,8BITMIME,SIZE,STARTTLS",,pmta-vmta0,,,gmail.com/pmta-vmta0,pmta-pool

[root@server bouncehandler]# cat /var/log/pmta/acct-2018-10-20-0000.csv  | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php --debug
[20/Oct/2018 13:51:02] ------------------------------------------------------------------
[20/Oct/2018 13:51:02] Port25 PowerMTA bounce-handler
[20/Oct/2018 13:51:02] (C) 2016-2017 Gerd Naschenweng  https://github.com/magicdude4eva
[20/Oct/2018 13:51:02] ------------------------------------------------------------------
[20/Oct/2018 13:51:02] Handling bounce categories=bad-mailbox,bad-domain,routing-errors,inactive-mailbox,spam-related,policy-related
[20/Oct/2018 13:51:02] Soft-bounce categories=bad-configuration,bad-connection,content-related,invalid-sender,other,policy-related,quota-issues,spam-related,virus-related
[20/Oct/2018 13:51:02] Bounce-provider: MailWizz, initialising
[20/Oct/2018 13:51:02]    Endpoint-URL=http://sendboxpro.win/mw/api/
[20/Oct/2018 13:51:02]    MailWizz enabled!
[20/Oct/2018 13:51:02] Bounce-provider: MailWizz, complete
[20/Oct/2018 13:51:02] Starting bounce processing
[20/Oct/2018 13:51:02] Completed bounce processing! Total records=5, processed=0, skipped=5
[root@server bouncehandler]#

**Comment by eyalschiffer** [comment]
I have the same problem. All configured and seems fine but no change is shown in MailWizz.

I see no bounces nor unsubscribes.

**Comment by informdev** [comment]
^^ Same problem as above. Everything seems right and manually processing them seems to work but no changes reflected in MailWizz.

**Comment by Mohit1946** [comment]
I am also facing same kind of issue,

Please see


[root@mail pmta]# echo "test@test.com" | /usr/bin/php /opt/pmta/bouncehandler/bouncehandler.php --debug
[25/Sep/2020 12:18:26] ------------------------------------------------------------------
[25/Sep/2020 12:18:26] Port25 PowerMTA bounce-handler
[25/Sep/2020 12:18:26] (C) 2016-2017 Gerd Naschenweng  https://github.com/magicdude4eva
[25/Sep/2020 12:18:26] ------------------------------------------------------------------
[25/Sep/2020 12:18:26] Handling bounce categories=bad-mailbox,bad-domain,routing-errors,inactive-mailbox,spam-related,policy-related
[25/Sep/2020 12:18:26] Soft-bounce categories=bad-configuration,bad-connection,content-related,invalid-sender,other,policy-related,quota-issues,spam-related,virus-related
[25/Sep/2020 12:18:26] Bounce-provider: Interspire, initialising
[25/Sep/2020 12:18:26]    Skipped - not configured!
[25/Sep/2020 12:18:26] Bounce-provider: MailWizz, initialising
[25/Sep/2020 12:18:26]    Endpoint-URL=http://mail.welcomefriend.co/wiz/api/index.php
PHP Fatal error:  Uncaught Error: Class 'MailWizzApi_Config' not found in /opt/pmta/bouncehandler/providers/bounce-provider-mailwizz.php:53
Stack trace:
#0 /opt/pmta/bouncehandler/bouncehandler.php(109): require_once()
#1 {main}
  thrown in /opt/pmta/bouncehandler/providers/bounce-provider-mailwizz.php on line 53



**I was also test with an CSV file**


[root@mail pmta]# cat /root/eufr-subscribers-rg746b35rkf98.csv | /usr/bin/php ./bouncehandler/bouncehandler.php 
[25/Sep/2020 06:19:01] ------------------------------------------------------------------
[25/Sep/2020 06:19:01] Port25 PowerMTA bounce-handler
[25/Sep/2020 06:19:01] (C) 2016-2017 Gerd Naschenweng  https://github.com/magicdude4eva
[25/Sep/2020 06:19:01] ------------------------------------------------------------------
[25/Sep/2020 06:19:01] Handling bounce categories=bad-mailbox,bad-domain,routing-errors,inactive-mailbox,spam-related,policy-related
[25/Sep/2020 06:19:01] Soft-bounce categories=bad-configuration,bad-connection,content-related,invalid-sender,other,policy-related,quota-issues,spam-related,virus-related
[25/Sep/2020 06:19:01] Bounce-provider: Interspire, initialising
[25/Sep/2020 06:19:01]    Skipped - not configured!
[25/Sep/2020 06:19:01] Bounce-provider: MailWizz, initialising
[25/Sep/2020 06:19:01]    Endpoint-URL=http://mail.welcomefriend.co/wiz/api/index.php
PHP Fatal error:  Uncaught Error: Class 'MailWizzApi_Config' not found in /opt/pmta/bouncehandler/providers/bounce-provider-mailwizz.php:53
Stack trace:
#0 /opt/pmta/bouncehandler/bouncehandler.php(109): require_once()
#1 {main}
  thrown in /opt/pmta/bouncehandler/providers/bounce-provider-mailwizz.php on line 53


I am using Php 7.4
and pmta version 4.5r11

Please help me to solve it,
